services:
  jenkins:
    image: jenkins/jenkins:2.495-jdk21 # Aqui você já escolhe a versão base do Java    
    container_name: jenkins-biblioteca
    privileged: true
    user: root
    ports:
      - "8008:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Permite que o Jenkins use o Docker do host